<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {

            // $table->string('meta_favorite_color')->virtualAs('meta->>"$.favorite_color"');
            // $table->index('meta_favorite_color');
            $table->increments('id');
            $table->string('unique_system_id')->index(); // this field is generated by the system and stays the same when dublicating the product
            $table->unsignedInteger('brand_id')->index();
            $table->unsignedInteger('category_id')->index();
            $table->unsignedInteger('supplier_id')->index()->nullable();
            $table->text('image_url')->nullable(); // an array of images 
            $table->json('media_files')->nullable(); // an array of images 

            $table->string('label')->index();
            $table->text('description')->nullable();
            $table->json('attributes_values')->nullable(); // an array, its keys are from the categories_attributes table and the value depends on each product
            $table->string('model')->index()->nullable(); // product model

            /** 
             * UPC is a standard serial number for the product world wide
             * UPC must change every time a attributes of the product change
             * https://www.instantupccodes.com/how-many-upc-codes-do-i-need.php
            */
            $table->string('upc')->index()->nullable(); 

            /**
             *  SKU is auto generated from product information
             *  Part of vendor / supplier name / 2 Characters
             *  Part of barnd name / 2 Characters
             *  Part of category / 2 Characters
             *  Part of label / 2 Characters
             *  increment number
            */
            $table->string('sku')->index();
            $table->unsignedInteger('product_status_id')->index()->default(0);

            // Finance Section
            $table->decimal('buy_price', 22, 2)->index()->nullable(); //90000.00
            
            $table->decimal('discount_price', 22, 2)->index()->default(0); //90000.00
            $table->decimal('discount_percent', 5, 2)->index()->default(0); //90000.00
            $table->decimal('profit_percent', 5, 2)->index()->default(0); //100.00 // 5
            $table->decimal('profit_amount', 22, 2)->index()->default(0); //90000.00

            $table->decimal('sell_price', 22, 2)->index()->nullable(); //90000.00 sell price can't be change by the user

            // HTT without VAT / Taxes
            // TTC with VAT / Taxes
            $table->unsignedInteger('low_quantity_value')->default(0);
            $table->boolean('alert_on_low_quantity')->default(true);
            $table->boolean('product_has_quantity')->default(true);
            $table->boolean('has_weight')->default(true);
            // $table->json('product_suppliers'); // an array, its keys are from the categories_attributes table and the value depends on each product

            $table->integer('stock_quantity')->index()->default(0);
            $table->unsignedInteger('weight_gm')->default(0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
